
@host = http://localhost:3000
# @host = https://dev.mydomain.com
# @host = https://mydomain.com

### get books (읽기)
GET {{host}}/api/books?searchStr=

### add book (추가)
POST {{host}}/api/books

{"title":"Sample Book", "writer":"lee"}

### get a book (읽기)
GET {{host}}/api/books/1

### update book (수정)
PUT {{host}}/api/books/1
# PATCH {{host}}/api/books/1

### remove book (삭제)
DELETE {{host}}/api/books/1

### get ttt
GET {{host}}/api/ttt?q=111